### ISSUE TITLE
ng g component Not Working

### ISSUE THREAD

**Issue by guslalo** [aveferrum/angular-material-demo#63]
hi my friend, ng g component Not Working. 
this error:

"Error: More than one module matches. Use skip-import option to skip importing the component into the closest module.
More than one module matches. Use skip-import option to skip importing the component into the closest module."

what I do?

**Comment by aveferrum** [comment]
Hi @guslalo 

While creating a new component, please specify the module name you'd like to import the component to. 

 `ng generate component componentName --module=app.module`

This will create and import `componentName` into `app.module.ts`

**Comment by guslalo** [comment]
thanks you!!!
